spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_user
    password: dev_pass

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
